export const GET_DOCTOR = "GET_DOCTOR"
export const GET_DOCTORS = "GET_DOCTORS"
export const POST_DOCTOR = "POST_DOCTOR"
export const PUT_DOCTOR = "PUT_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const POST_PACIENTE = "POST_PACIENTE"
export const GET_PACIENTES = "GET_PACIENTES"
export const GET_PACIENTE = "GET_PACIENTE"
export const GET_USER = "GET_USER"
export const GET_USERS = "GET_USERS"
export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"
export const POST_TURNO = "POST_TURNO"
export const GET_TURNOS = "GET_TURNOS"
export const DELETE_TURNO = "DELETE_TURNO"

export const URL_DB = ""