export { Navbarr } from './navbar'
export { Footerr } from './footer'
export { SacarTurno } from './sacarTurno'
export { SectionDoctorsMain } from './sectionDoctorsMain'
export { BuscarTurnos } from './buscarTurnos'
export { AprobarDoctor } from './aprobarDoctor'
export { MostrarUsuarios } from './mostrarUsuarios'
export { AdminEspecialidades } from './adminEspecialidades'